name: myenv
channels:
  - conda-forge
dependencies:

  - python=3.12.4
  - voila
  - jupyterlab
  - pandas
  - matplotlib
  - bqplot
  - ipympl
  - ipyvolume
  - scipy
  - pip
  - swi-prolog
  - ipywidgets
  - tk
  - pillow
  - ipython
  - pip:
    - swiplserver
    - tkinter
