services:
  jupyterlab:
    image: jupyter/base-notebook:latest
    container_name: jupyterlab
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./notebooks:/home/jovyan/work

  voila:
    image: python:3.12
    container_name: voila
    ports:
      - "8866:8866"  # Puedes cambiar el puerto si es necesario
    volumes:
      - ./notebooks:/home/app/notebooks
    working_dir: /home/app
    command: >
      bash -c "pip install voila && voila --port=8866 --no-browser /home/app/notebooks"

  swi-prolog:
    image: swipl:latest
    container_name: swi-prolog
    ports:
      - "3020:3020"
    command: ["swipl"]
