name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - swi-prolog
  - python=3.12.4
  - voila=0.5.1
  - jupyterlab
  - pandas
  - matplotlib
  - bqplot
  - ipympl
  - ipyvolume
  - scipy
  - pip
  - pip:
    - pyswip
    - swiplserver==1.0.2